docs:
- any: ['doc/**/*']

examples:
- any: ['examples/**/*']

benchmarks:
- any: ['tests/benchmarks/**/*']

unit-tests:
- any: ['tests/unit/**/*']

cmake:
- any: ['cmake/**/*']

mmg:
- any: ['src/RodinExternal/MMG/**/*']

geometry:
- any: ['src/Rodin/Geometry/**/*']

variational:
- any: ['src/Rodin/Variational/**/*']

solver:
- any: ['src/Rodin/Solver/**/*']

utility:
- any: ['src/Rodin/Utility/**/*']

context:
- any: ['src/Rodin/Context/**/*']

form-language:
- any: ['src/Rodin/FormLanguage/**/*']

math:
- any: ['src/Rodin/Math/**/*']

io:
- any: ['src/Rodin/IO/**/*']

alerts:
- any: ['src/Rodin/Alert/**/*']

qf:
- any: ['src/Rodin/QF/**/*']

plot:
- any: ['src/Rodin/Plot/**/*']
