docs:
- any: ['doc/**/*']

examples:
- any: ['examples/**/*']

cmake:
- any: ['cmake/**/*']

mmg:
- any: ['src/RodinExternal/MMG/**/*']

geometry:
- any: ['src/Rodin/Geometry/**/*']

variational:
- any: ['src/Rodin/Variational/**/*']

solver:
- any: ['src/Rodin/Solver/**/*']

utility:
- any: ['src/Rodin/Utility/**/*']

core:
- any: ['src/Rodin/Core/**/*']

alerts:
- any: ['src/Rodin/Alert/**/*']

plot:
- any: ['src/Rodin/Plot/**/*']
