name: Benchmarks
on:
  push:
    branches:
      - master
      - develop

concurrency:
  group: Benchmarks-${{ github.ref }}
  cancel-in-progress: true
  
permissions:
  deployments: write
  contents: write

jobs:
  Ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc-8]
        build_type: ['Release']
      fail-fast: false
    env:
      MAKEFLAGS: "-j2"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: >-
          sudo apt-get update && sudo apt-get install -y
          libgl1-mesa-dev
          lcov
          libsdl2-dev
          libglfw3-dev
          libopenal-dev
          libvulkan-dev
          libsuitesparse-dev
          libmetis-dev
          libboost-all-dev
      - name: Configure CMake
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DRODIN_BUILD_DOC=OFF
          -DRODIN_USE_MCSS=OFF
          -DRODIN_BUILD_EXAMPLES=OFF
          -DRODIN_BUILD_UNIT_TESTS=OFF
          -DRODIN_CODE_COVERAGE=OFF
          -DRODIN_BUILD_SRC=ON
          -DRODIN_BUILD_BENCHMARKS=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: Run benchmarks
        run: ${{github.workspace}}/build/tests/benchmarks/RodinBenchmarks --benchmark_format=json --benchmark_out=${{github.workspace}}/RodinBenchmarks.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: C++ Rodin Benchmarks
          tool: 'googlecpp'
          output-file-path: ${{github.workspace}}/RodinBenchmarks.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          comment-on-alert: true
          alert-threshold: "150%"
          benchmark-data-dir-path: benchmarks/${{ github.ref }}
        
