name: Static Analysis

on:
  push:
    branches:
      - master
      - develop

concurrency:
  group: StaticAnalysis-${{ github.ref }}
  cancel-in-progress: true

permissions:
  deployments: write
  contents: write

jobs:
  IncludeDependencyGraph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup destination path
        run: mkdir -p static/dev/${{ github.ref }}
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          cache: 'pip'
      - run: pip install -r dev/Requirements.txt
      - name: Execute script
        run: |
          mkdir -p static/dev/${{ github.ref }}
          python ${{github.workspace}}/dev/include_dependency_graph.py ${{github.workspace}}/src --svg=static/dev/${{ github.ref }}/IncludeDependencyGraph.svg --dot=static/dev/${{ github.ref }}/IncludeDependencyGraph.dot
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: IncludeDependencyGraph
          path: |
            static/dev/${{ github.ref }}/IncludeDependencyGraph.dot
            static/dev/${{ github.ref }}/IncludeDependencyGraph.svg
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: static/dev/${{ github.ref }}
          destination_dir: static/dev/${{ github.ref }}/IncludeDependencyGraph
