name: Ubuntu 18.04 GCC 8
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  Build-Rodin:
    runs-on: ubuntu-18.04
    env:
      MAKEFLAGS: "-j2"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup gcc-8
        uses: egor-tensin/setup-gcc@v1
        with:
            version: 8
            platform: x64
      - name: Install dependencies
        run: >-
          sudo apt-get update && sudo apt-get install -y
          libgl1-mesa-dev
          lcov
          libsdl2-dev
          libglfw3-dev
          libopenal-dev
          libvulkan-dev
          libsuitesparse-dev
      - name: Configure CMake
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=Release
          -DRODIN_BUILD_DOC=OFF
          -DRODIN_USE_MCSS=OFF
          -DRODIN_BUILD_SRC=ON
          -DRODIN_BUILD_EXAMPLES=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build
  Generate-Badge:
      if: ${{ always() && github.ref == 'refs/heads/master' }}
      needs: Build-Rodin
      runs-on: ubuntu-latest
      steps:
        - name: Generate succesful build badge
          if: needs.Build-Rodin.result == 'success'
          uses: RubbaBoy/BYOB@v1.2.1
          with:
            NAME: Ubuntu-18_04-gcc-8-build_badge
            LABEL: 'build'
            STATUS: 'success'
            COLOR: 50C828
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Generate failing build badge
          if: needs.Build-Rodin.result == 'failure'
          uses: RubbaBoy/BYOB@v1.2.1
          with:
            NAME: Ubuntu-18_04-gcc-8-build_badge
            LABEL: 'build'
            STATUS: 'failure'
            COLOR: red
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Generate cancelled build badge
          if: needs.Build-Rodin.result == 'cancelled'
          uses: RubbaBoy/BYOB@v1.2.1
          with:
            NAME: Ubuntu-18_04-gcc-8-build_badge
            LABEL: 'build'
            STATUS: 'cancelled'
            COLOR: 9B9B9B
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Generate skipped build badge
          if: needs.Build-Rodin.result == 'skipped'
          uses: RubbaBoy/BYOB@v1.2.1
          with:
            NAME: Ubuntu-18_04-gcc-8-build_badge
            LABEL: 'build'
            STATUS: 'skipped'
            COLOR: D9AE2D
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

